# Matrices and Vectors

### Matrix - definition
For all intents and purposes, a matrix is simply an object that consists of elements ordered in such a way that the entries in the matrix create a structure of m rows and n columns. <br>
Let $A$ be a matrix with $m$ rows and $n$ columns. The entries of $A$ are denoted by $a_{ij}$, where $i$ shows on which row that specific element is located, and in a similar fasion $j$ shows which column. Thus we have:

$$ A = \begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \end{bmatrix} $$

We say that $A$ is an $m \times n$ matrix, or that $A$ has size $m \times n$. If $m = n$, we say that $A$ is a square matrix.

 

As a clariftying example, Let $A$ be a 2x3 matrix with entries $a_{ij}$ 

$$ A = \begin{bmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \end{bmatrix} = \begin{bmatrix} 2 & -5 & 8 \\ -1 & 7 & 0 \end{bmatrix} $$

In this example, the entries of the matrix are real valued integers given by: <br>
$a_{11} = 2$, $a_{12} = -5$, $a_{13} = 8$, $a_{21} = -1$, $a_{22} = 7$, and $a_{23} = 0$. 

In [69]:
# Create the matrix using python
import numpy as np
A = np.array([[2,-5,8],[-1,7,0]])
print("Matrix A:")
print(A)

Matrix A:
[[ 2 -5  8]
 [-1  7  0]]


And here is another example: <br>
    Let $B$ be a 3x2 matrix with real number entries $b_{ij}$. Then we have:

$$ B = \begin{bmatrix} b_{11} & a_{12} \\ b_{21} & a_{22} \\ b_{31} & b_{32} \end{bmatrix} = \begin{bmatrix} 1.2 & -0.5 \\ 0 & 4.7 \\ -2.1 & 3.3 \end{bmatrix} $$

In this example, the entries of the matrix are real-valued numbers given by: <br> 
$b_{11} = 1.2$, $b_{12} = -0.5$, $b_{21} = 0$, $b_{22} = 4.7$, $b_{31} = -2.1$, and $b_{32} = 3.3$. 

In [70]:
# Create the matrix using python
B = np.array([[1.2, -0.5], [0, 4.7], [-2.1, 3.3]])
print("Matrix B:")
print(B)

Matrix B:
[[ 1.2 -0.5]
 [ 0.   4.7]
 [-2.1  3.3]]


### Vector - definition
A vector is a special kind of matrix that consists of either one row (called row vector) or one column (called column vector).
Given $\vec{u}$ and $\vec{v}$ as:
$$ \vec{u} = \begin{bmatrix} u_1 & u_2 & u_3 \end{bmatrix} \quad \text{and} \quad \vec{v} = \begin{bmatrix} v_1 \\ v_2 \\ v_3 \end{bmatrix} $$
Here $\vec{u}$ is a row vector while $\vec{v}$ is a column vector. <br>
As an example, we could have $\vec{u} = \begin{bmatrix} 3 & -4 & 2 \end{bmatrix}$ and $\vec{v} = \begin{bmatrix} -1 \\ 5 \\ -2 \end{bmatrix}$.


### Matrix addition
Matrix addition (needless to say that subtraction follows the same rule) is done entry-wise and hence the matrices must have the same dimentionality. 
One can not for instance add a $2\times 3$ matrix with a $3 \times 2$ matrix. Same goes for vectors. <br>
Let $A$ and $B$ be two 2x3 matrices with entries $a_{ij}$ and $b_{ij}$, respectively. Then we can add these matrices entry-wise to obtain the sum $C = A + B$:

$$
A = \begin{bmatrix} 2 & 6 & -8 \\ -7 & 3 & 1 \end{bmatrix} \quad \text{and} \quad B = \begin{bmatrix} 5 & -2 & 4 \\ 0 & -5 & 9 \end{bmatrix}
$$

To compute $C = A + B$, we add the corresponding entries of $A$ and $B$:

$$
C = A + B = \begin{bmatrix} 2+5 & 6+(-2) & (-8)+4 \\ (-7)+0 & 3+(-5) & 1+9 \end{bmatrix} = \begin{bmatrix} 7 & 4 & -4 \\ -7 & -2 & 10 \end{bmatrix}
$$

In [71]:
# Python
A = np.array([[2,6,-8],[-7,3,1]])
B = np.array([[5,-2,4],[0,-5,9]])
C = A + B
print("C = A + B:\n", C)

C = A + B:
 [[ 7  4 -4]
 [-7 -2 10]]


# Matrix transpose
When transposing a matrix, the rows of the matrix become simply its columns and vise versa. <br>
Let $A$ be a 3x4 matrix. Then the transpose of $A$, denoted by $A^T$, is obtained by interchanging its rows and columns.

For example, consider the following matrix:

$$
A = \begin{bmatrix}
-3 & 5 & 1 & -6 \\
0 & 2 & -2 & 6 \\
4 & 3 & -5 & -3 \\
\end{bmatrix}
$$

To find the transpose of $A$, we interchange its rows and columns:

$$
A^T = \begin{bmatrix}
-3 & 0 & 4 \\
5 & 2 & 3 \\
1 & -2 & -5 \\
-6 & 6 & -3 \\
\end{bmatrix}
$$

Therefore, the transpose of $A$ is $A^T = \begin{bmatrix} -3 & 0 & 4 \\ 5 & 2 & 3 \\ 1 & -2 & -5 \\ -6 & 6 & -3 \end{bmatrix}$.


In [73]:
# Python
A = np.array([[-3,5,1,-6],[0,2,-2,6],[4,3,-5,-3]])
# A transpose
A_t = np.transpose(A)
print("Transposed matrix A_t:\n", A_t)

Transposed matrix A_t:
 [[-3  0  4]
 [ 5  2  3]
 [ 1 -2 -5]
 [-6  6 -3]]


So logically, when transposing a row vector one obtains a column vector and vise versa. With the previously given vectors:
<br>
<br>
  $\vec{v} = \begin{bmatrix} -1 \\ 5 \\ -2 \end{bmatrix} \quad 
  \vec{v}^{T} =  \begin{bmatrix} -1 & 5 & -2 \end{bmatrix} $ <br>

### Scalar product
When taking the scalar product of two vectors one obtains a scalar (i e a number). This is accomplished by multiplying the first entry in the first vector with the first entry in the second vector, the second with the second and so on, and finaly sum all the products. <br>

The scalar product (or dot product) of two vectors $\vec{u}$ and $\vec{v}$ is defined as the sum of the products of their corresponding entries. 
<br>
If $\vec{u} = \begin{bmatrix} u_1 & u_2 & u_3 \end{bmatrix}$ and $\vec{v} = \begin{bmatrix} v_1 \\ v_2 \\ v_3 \end{bmatrix}$, 
<br>
then the scalar product of $\vec{u}$ and $\vec{v}$, denoted by $\vec{u} \cdot \vec{v}$, is given by: 

$$
\vec{u} \cdot \vec{v} = u_1v_1 + u_2v_2 + u_3v_3.
$$

Using this formula, we can compute the scalar product of the vectors $\vec{u} = \begin{bmatrix} 3 & -4 & 2 \end{bmatrix}$ and $\vec{v} = \begin{bmatrix} -1 \\ 5 \\ -2 \end{bmatrix}$ as follows:

$$
\begin{aligned}
\vec{u} \cdot \vec{v} &= (3)(-1) + (-4)(5) + (2)(-2) \\
&= -3 - 20 - 4 \\
&= -27
\end{aligned}
$$

Therefore, the scalar product of the vectors $\vec{u}$ and $\vec{v}$ is $\vec{u} \cdot \vec{v} = -27$.
<br>
One can easily see that for this to work, the number of entries in both vectors must be the same.

In [74]:
# Python
u = np.array([3,-4,2])
v = np.array([-1,5,-2])
w = np.dot(u,v)
print("w =", w)

w = -27


### Matrix multiplication
When multiplying two matrices keep in mind, rows scalar product columns.

<br>
Given two matrices $A$ and $B$, their product $C = AB$ is defined if and only if the number of columns of $A$ is equal to the number of rows of $B$. The resulting matrix $C$ will have the same number of rows as $A$ and the same number of columns as $B$. 
<br>
For clarity, the entries in matrix $C$ given next will be: <br>

$c_{11} = row_{1} \cdot col_{1} $ <br>
$c_{12} = row_{1} \cdot col_{2}$ <br>
$c_{21} = row_{2} \cdot col_{1} $<br>
$c_{22} = row_{2} \cdot col_{2} $<br>

Consider the following two matrices:

$$
A = \begin{bmatrix}
2 & -3 & 1 \\
4 & 5 & -2 \\
\end{bmatrix}
\quad \text{and} \quad
B = \begin{bmatrix}
-1 & 2 \\
3 & 0 \\
-2 & 1 \\
\end{bmatrix}
$$


To find their product $C = AB$, we multiply the rows of $A$ by the columns of $B$ as follows:

$$
\begin{aligned}
C &= AB \\
&= \begin{bmatrix} 2 & -3 & 1 \\ 4 & 5 & -2 \end{bmatrix} \begin{bmatrix} -1 & 2 \\ 3 & 0 \\ -2 & 1 \end{bmatrix} \\
&= \begin{bmatrix} (2)(-1) + (-3)(3) + (1)(-2) & (2)(2) + (-3)(0) + (1)(1) \\ (4)(-1) + (5)(3) + (-2)(-2) & (4)(2) + (5)(0) + (-2)(1) \end{bmatrix} \\
&= \begin{bmatrix} -13 & 5 \\ 15 & 6 \end{bmatrix}
\end{aligned}
$$

Therefore, the product of the two matrices $A$ and $B$ is $C = \begin{bmatrix} -13 & 5 \\ 15 & 6 \end{bmatrix}$.


In [75]:
# Python
A = np.array([[2,-3,1],[4,5,-2]])
B = np.array([[-1,2],[3,0],[-2,1]])
D = np.array([[2, -3, 1], [4, 5, -2]])
F = np.array([[-1, 2], [3, 0], [-2, 1]])

C = np.dot(D, F)
print("C = ", C)

C =  [[-13   5]
 [ 15   6]]


### Matrix vector multiplication
Finally here is how one multiplies a matrix with a vector. <br>
Given a matrix $A$ and a vector $\vec{v}$: 
<br>

$$A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
 \quad \text{and} \quad \vec{v} = \begin{bmatrix} 1 & 2 & 3  \end{bmatrix},
$$ <br>

multiplying $\matrix{A}$ with $\vec{v}$ yields:

$$
\begin{aligned}
A\vec{v} = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
\begin{bmatrix}
1 \\
2 \\
3
\end{bmatrix}
=
\begin{bmatrix}
1\cdot 1 + 2 \cdot 2 + 3 \cdot 3 \\
4 \cdot 1 + 5 \cdot 2 + 6 \cdot 3 \\
7 \cdot 1 + 8 \cdot 2 + 9 \cdot 3
\end{bmatrix}
=
\begin{bmatrix}
14 \\
32 \\
50
\end{bmatrix}
\end{aligned}
$$

Notice how even here the rule of rows from the first object are multiplied with in this case the only vector from the other object.

In [58]:
import numpy as np

# Define matrix A and vector v
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
v = np.array([1, 2, 3])

# Compute the product Av
Av = np.dot(A, v)

print(Av)


[14 32 50]
